# Generated by Django 3.0.2 on 2021-02-06 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(blank=True, default=None, null=True)),
                ('user_id', models.IntegerField(default=0)),
                ('dialog', models.TextField(default='start')),
                ('balance', models.DecimalField(decimal_places=0, default=100, max_digits=32)),
                ('temp', models.TextField(default='')),
                ('reg_date', models.TextField(default='2021.02.06 10:12')),
                ('hyperlink', models.BooleanField(default=True)),
            ],
        ),
    ]
