# Generated by Django 3.0.2 on 2021-03-13 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='reg_date',
            field=models.TextField(default='2021.03.13 09:10'),
        ),
    ]
