# Generated by Django 3.0.2 on 2021-03-13 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210313_0610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='reg_date',
            field=models.TextField(default='2021.03.13 09:28'),
        ),
    ]
