# Generated by Django 3.0.2 on 2021-03-13 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210313_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='farm',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='reg_date',
            field=models.TextField(default='2021.03.13 16:47'),
        ),
    ]
