# Generated by Django 3.0.2 on 2021-03-13 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210313_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='reg_date',
            field=models.TextField(default='2021.03.13 16:48'),
        ),
    ]
